# Generated by Django 6.0.1 on 2026-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_cv_user_remove_skill_cv_remove_education_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='template_id',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_chosen',
            field=models.CharField(default='template1', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='color_scheme',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
    ]
