# Generated by Django 6.0.1 on 2026-04-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
