# Generated by Django 6.0.1 on 2026-04-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_resume_updated_at_delete_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='status',
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size_details',
            field=models.CharField(default='14', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size_heading',
            field=models.CharField(default='16', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size_name',
            field=models.CharField(default='18', max_length=10),
        ),
    ]
