# Generated by Django 6.0.1 on 2026-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_remove_resume_font_size_remove_resume_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='font_size_details',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='font_size_heading',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='font_size_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size',
            field=models.CharField(choices=[('14', '14px'), ('16', '16px'), ('18', '18px'), ('20', '20px'), ('22', '22px')], default='16', max_length=10),
        ),
    ]
