# Generated by Django 6.0.1 on 2026-04-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_remove_resume_font_size_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='font_size',
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size_details',
            field=models.CharField(choices=[('12', '12px'), ('13', '13px'), ('14', '14px'), ('15', '15px'), ('16', '16px'), ('17', '17px')], default='16', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size_heading',
            field=models.CharField(choices=[('14', '14px'), ('16', '16px'), ('18', '18px'), ('20', '20px'), ('22', '22px'), ('24', '24px')], default='18', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='font_size_name',
            field=models.CharField(choices=[('18', '18px'), ('20', '20px'), ('22', '22px'), ('24', '24px'), ('26', '26px'), ('28', '28px')], default='20', max_length=10),
        ),
    ]
