# Generated by Django 6.0.1 on 2026-04-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_remove_resume_font_size_resume_font_size_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_year',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='end_date',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
    ]
