# Generated by Django 6.0.1 on 2026-04-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_rename_end_year_education_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='duration',
            new_name='edu_duration',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='duration',
            new_name='exp_duration',
        ),
    ]
